### ISSUE TITLE
Better handling of empty sensor

### ISSUE THREAD

**Issue by frankysan** [Miicroo/lovelace-vasttrafik-card#14]
I have a sensor for a bus that runs at certain time intervals, and only on weekdays. This means that the sensor is undefined for all other times. This results in a line that doesn't get rendered properly on the card.

This is my code for the card:
```
type: custom:vasttrafik-card
title: Bussavgångar
entities:
  - sensor.17_mot_stan
  - sensor.44_mot_stan
municipality: Göteborg
sort: true
showFrom: false
showTo: false
showDir: true
```

The code for sensors:
```
- platform: vasttrafik
  key: !secret vasttrafik_api_key
  secret: !secret vasttrafik_api_secret
  departures:
    - name: 17, Mot stan
      from: Norumsgärde
      heading: Tuve torg
      delay: 5
      lines:
        - 17
    - name: 44, Mot stan
      from: Norumsgärde
      heading: Tuve torg
      delay: 5
      lines:
        - 44
```

The resulting card:
![vasttrafik](https://github.com/Miicroo/lovelace-vasttrafik-card/assets/6353605/d9209629-3237-4b6d-af23-e96886def100)

I'm not really a programmer, more of a hobby hacker, but I'll see what I can do myself on my branch.
